library(tidyverse)
library(readr)
chic <- read_csv("data-raw/chic.csv")
diabetes <- read_csv("data-raw/diabetes.csv")
trop_long_na <- read_csv("data-raw/trop.long.na.csv")
trop <- trop_long_na %>%
  select(c(1:4,8,20,33,34))
i <- which(trop$cTnT == 3)
trop$cTnT[i] <- runif(i, 0, 3)
trop <- trop %>% mutate(creat = case_when( pt.id== 1 ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 2  ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 3  ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 4 ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 5 ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 6  ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 7  ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 8 ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 9 ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 10 ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 11 ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 12  ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 13  ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 14 ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 15 ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 16 ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 17 ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 18  ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 19  ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 20 ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 21 ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 22  ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 23  ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 24 ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 25 ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 26 ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 27 ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 28  ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 29  ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 30 ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 31 ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 32  ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 33  ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 34 ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 35 ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 36 ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 37 ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 38  ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 39  ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 40 ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 51 ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 52  ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 53  ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 54 ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 55 ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 56 ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 57 ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 58  ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 59  ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 60 ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 41 ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 42  ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 43  ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 44 ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 45 ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 46 ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 47 ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 48  ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 49  ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 50 ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 61 ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 62  ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 63  ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 64 ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 65 ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 66 ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 67 ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 68  ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 69  ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 70 ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 71 ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 72  ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 73  ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 74 ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 75 ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 76 ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 77 ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 78  ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 79  ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 80 ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 81 ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 82  ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 83  ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 84 ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 85 ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 86 ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 87 ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 88  ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 89  ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 90 ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 91 ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 92  ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 93  ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 94 ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 95 ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 96 ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 97 ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 98  ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 99  ~ rnorm(1491, Labo_Creatinine,5),
                                          pt.id== 100 ~ rnorm(1491, Labo_Creatinine,5),
                                  TRUE ~ 0))

trop <- trop %>%
  mutate( creat = ifelse(time==1, Labo_Creatinine, creat)) %>%
  select(-Labo_Creatinine)
usethis::use_data(chic,card, diabetes, trop, overwrite = TRUE)



